#
#    Copyright 2010-2023 the original author or authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /jpetstore

# Install dos2unix to handle Windows line endings
RUN apt-get update && apt-get install -y dos2unix

# Copy Maven wrapper files
COPY .mvn/ .mvn/
COPY mvnw mvnw.cmd pom.xml format.xml renovate.json ./

# Convert line endings and set permissions
RUN dos2unix mvnw && chmod +x mvnw

# Copy source code and build
COPY ./src ./src
RUN ./mvnw clean package

CMD ["./mvnw", "cargo:run", "-P", "tomcat90"]
